name: Publish Package to npmjs
on:
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v6
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v6
              with:
                  cache: npm
                  node-version: '24.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: npm ci
            - run: npm -w ./packages/deepcover run build
            - run: npm -w ./packages/deepcover publish --tag alpha
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
